### ISSUE TITLE
[FEAT] Create an Endpoint to Retrieve Blog Articles 

### ISSUE THREAD

**Issue by AsciencioAlex** [hngprojects/hng_boilerplate_nestjs#160] opened 2024-07-17 16:36 UTC
## Description
 Create an API endpoint that allows users to retrieve blog articles.

## Acceptance Criteria
- [ ] The endpoint should support fetching all articles.
- [ ] The response should include article metadata such as title, author, category, publication date, an excerpt, cover photo, and read time.
- [ ] The response should be paginated to handle large numbers of articles efficiently.

#### Successful Response
```
{
  "status": "success",
  "data": {
    "articles": [
      {
        "id": 1,
        "title": "Article 1 HNG boilerplate",
        "author": "Prince Kingsley Asciencio",
        "publication_date": "July 17, 2024",
        "category": "Technology",
        "excerpt": "Article excerpt content",
        "content": "Full article content goes here...",
        "url": "/blog/article1",
        "cover_photo": "cover_photo.png"
      }
    ]
  }
}
```
#### Unsuccessful Request
```
{
  "message": "Error retrieving articles",
  "errors": [
    "Invalid author name format",
    "Category not found",
    "Invalid date format"
  ],
  "status_code": 500
}
```

### Purpose
The purpose of this endpoint is to provide a way for users to easily access and retrieve blog articles from our database. This will enable the creation of a more dynamic and interactive blog section on our website.

### Requirem#ents	
- The endpoint should be a GET request to `/api/articles`.
- The response should be in JSON format.
- The response should include necessary metadata for each article.
- The response should be paginated.
- Appropriate status codes should be returned for successful `200 ok` and unsuccessful requests `500 server error`.

### Unit Tests
- Test fetching all articles without any filters.
- Test pagination functionality.
- Test error handling for invalid requests.

### Expected Outcome
- The endpoint is able to return a list of blog articles.
- The returned articles include all necessary metadata.
- The endpoint handles large datasets efficiently with pagination.
- The endpoint gracefully handles invalid requests with appropriate error messages.

            
                                 
![Copy of  HNG boilerplate](https://github.com/user-attachments/assets/20b0aec4-1302-4c5c-889d-51c301bdbecd)
@kvngstar

**Comment by Pythonian** [comment] 2024-07-17 16:40
Isn't this a duplicate of #94 ?

**Comment by Kvngstar** [comment] 2024-07-17 16:52
We searched the issues for this but we didn't see it before when worked on it. We will definitely work on another one. @Pythonian @buka4rill

**Comment by AsciencioAlex** [comment] 2024-07-17 17:08
Yes @Pythonian and @buka4rill we had done a thorough search on the github tickets. I think this one skipped us. We really appreciate both of you pointing out the duplicate issue. We apology for any inconvenience, however, just as my partner @Kvngstar  as stated, we have agreed to work on another ticket that has not been handled yet. Thanks

**Comment by markessien** [comment] 2024-07-18 04:29
if this is duplicated, delete it

**Comment by AsciencioAlex** [comment] 2024-07-18 09:02
@markessien  we can't see the delete button for this issue. We are working on another github ticket.

**Closed** 2024-07-29 13:04 UTC
Labels: duplicate, feature, Needs Revision
