### ISSUE TITLE
[FEAT] Endpoints for the about Page - Values, settable from admin

### ISSUE THREAD

**Issue by JumongComputers** [hngprojects/hng_boilerplate_nestjs#272] opened 2024-07-19 22:51 UTC
## Description
develop new API endpoints for managing the content of the About page. These endpoints will allow values on the "About" page to be fetched and updated via an admin interface.

## Acceptance Criteria

1.  GET /api/about-us endpoint is created.
2. PUT /api/about-us endpoint is created.
3. The GET endpoint returns a JSON response with mission, vision, values, history
4. The PUT endpoint accepts a JSON body with mission, vision, values, history, 
5. The PUT endpoint is accessible only to authenticated admin users.
6. Proper error handling is implemented for validation errors, database connection issues, and other potential errors.
7. The endpoints are documented in the API documentation.
8. Unit tests are written for the endpoints and they pass successfully.
9. Code review is performed and approved before merging the changes.

### Purpose
The purpose of this feature is to create API endpoints that allow admin users to fetch and update values displayed on the "About" page. This will enable dynamic content management, ensuring that information on the "About" page remains current and relevant. By providing these endpoints, admin users will have the ability to update the mission statement, vision statement, and core values of the organization as needed without requiring developer intervention.

### Requirem#ents	

- Create two API endpoints:

---GET /api/about-us/ Fetch the current content displayed on the "About" page.
---PUT /api/about-us/ Update the content displayed on the "About" page.
-The GET endpoint should return the following fields in JSON format:
---mission (string): The mission statement.
---vision (string): The vision statement.
---values (array of strings): The core values.
---history (string): The history of the organization.
-The PUT endpoint should accept a JSON body with the same fields and update the corresponding content in the database.
-Ensure that only authenticated admin users can access the PUT endpoint.
-Implement proper error handling for potential issues such as database connection errors and validation errors.

### Expected Outcome
-Functional and reliable GET /api/about-us/and PUT /api/about-us/ endpoints.
-The endpoints return and accept the required fields in JSON format.
-Only authenticated admin users can update the values.
-Proper error handling mechanisms are in place.

### Endpoints
[GET]`/api/v1/about/values:`

- **Description:** Fetch About us.
**-Success Response**
    - Status: `200 Ok`
    - Body

```json{
"mission": "To provide the best service.",
  "vision": "To be the leading provider in our industry.",
  "values": [
    "Integrity",
    "Customer Focus",
    "Innovation"
],

  "history": "Our company was founded in 1990 with the goal of providing exceptional service.",
}
```

-**Bad Response**
    - Status: `400 Bad response`
    - Body
 
 ```json
{
  "message": "Could not fetch about page",
  "status_code": 400
}

```
##[PUT]`/api/v1/about-us`

-**Description:** Update Values in about us
**-Success Response**
    - Status: `200 Ok`
    - Body

```json 
{

  "mission": "To provide exceptional service.",
  "vision": "To be the most trusted provider in our industry.",
  "values": [
    "Excellence",
    "Customer Satisfaction",
    "Creativity"
  ],
  "history": "Our company was founded in 1990 with a mission to provide exceptional service.",
}
```
-**Bad Request**
    - Status: `401 Invalid data`
    - Body
  ```json
{
  "message": "Could not update about page",
  "status_code": 401
}

```

**Comment by markessien** [comment] 2024-07-20 04:18
duplicate

**Comment by sethdanny** [comment] 2024-07-20 08:11
It's. A duplicate of the already approved one. https://github.com/hngprojects/hng_boilerplate_nestjs/issues/235

**Closed** 2024-08-19 20:12 UTC
Labels: feature
